# Note for the paper

ERGM toturial: 
https://www.r-bloggers.com/ergm-tutorial/

Bergm toturial:
http://acaimo.github.io/Bergm/tutorials/Dec_18.html

# Ergms
ERGM- consider transitivity by taking into account high-order k-triangles. Triangles and higher order cycles

# Explore different combination of variables for Bergm
1. there is difference in statistics (mean, sd) between weighed and unweighed ties
2. difference in statistics when simplifying variables to agate and golden beads, plus a few types of prestige goods such as gold foil and fish-like shaped necklace. The mean looks fine
3. did not work well when there is too many ties in the network
4. difference in the results of using BergmM and Bergm, BergmM is for missing data
5. add the spacial information?

# some paragraphs from proposal 
At Kiwulan, we view individual burials as actors or nodes in the social network, and use SNA methods to test hypotheses about the distribution of influence in the network to identify network or corporate mode conditions. Network ties will be drawn between burials with similar variables that can represent the same ‘community’ or social group. To measure change in social inequality, I will use the binary presence or absence of burial goods, the amount of prestige goods, grave dimensional attributes, and ordinal variables of age and sex categories to determine which actors have connections in the network (Sosna, et al. 2012).

Once the relationships between the actors have been described, I will compute statistical measures such as network degree centrality, graph density, and graph centralization. These measures are helpful to identify individual’s role and trends of network relationship, and I will use them to formally test hypotheses about the structure of the social network (Brughmans 2010: 280; Gjesfjeld 2014: 192). I predict that if there is a change from corporate to network mode following the European contact, then I expect the social network will show statistically significantly higher degrees of centrality and a higher density in the post-European period compared to pre-European period. This is because a social network graph that is highly centralized and very sparse indicates high concentrations of wealth, and higher social inequality.

# Testing the predictions of the models

My hypothesis is that if European colonization created monopolies for trade between a small number of indigenous people, and this resulted in the shift from a more corporate to a more network organization, then I would expect to see changes in mortuary practices, food consumption and feasting behaviors, and social network organization at Kiwulan.

Before European contact, households consisted of single and multi-family units and were organized in a corporate mode with limited economic inequality primarily based on age, gender, or different corporate groups. I expect that burial goods will reveal a relatively even distribution of the quantity and quality of items. Social network analysis will indicate multiple small groups of similar size. If there is unequal distribution of prestige or high quality goods, then it will be restricted to group who share similar demographic characteristics such as age. Production and consumption of ceramics will be based on corporate groups. Thus, diversity of sources and style of pottery within a family unit will be more similar than between family units. Activity areas of family units will reflect more even distribution of high ranked subsistence resources, and cache pits will present less variability in size and contents.

After European contact, there will be more obvious inequalities in the distribution of prestige materials in burials and settlement areas, indicative of an increase in the concentration of wealth at Kiwulan. Prestige goods will not only appear in adult burials but also child burials, which reflect wealth accumulation within a family. Higher quality imported goods will mainly appear in a few but not all individual burials because of control of long distance trade. Social network analysis of burials will present a higher density and higher degree of centrality based on individual power. Production and consumption of ceramics will extend beyond the corporate groups and present more standardized sizes and shapes, which show an emphasis on production for feasting, and control of production by a small number of individuals. Activity areas will reflect uneven distribution of high ranked subsistence resources, and cache pits will present higher variability in size and contents.

# acceptance rate
https://www.ibm.com/support/pages/acceptance-rate-amos-bayesian-sem
The acceptance rate is the proportion of times the Metropolis sampling algorithm generates a sample of parameter values that differs from the previous sample. For example, an acceptance rate of .2 means that, in generating a sequence of parameter values, the algorithm generates new parameter values 20% of the time and repeats the previous parameter values 80% of the time.

One rule of thumb is that the MCMC algorithm is most effective when the acceptance rate is between .2 and .5. If you see that the acceptance rate is outside this range, it may be worthwhile to try adjusting the tuning parameter. If the acceptance rate is less than .2, try making the tuning parameter smaller. If the acceptance rate is greater than .5, try making the tuning parameter larger.

